[package]
name = "meilisearch-error"
version = "0.24.0"
authors = ["marin <postma.marin@protonmail.com>"]
edition = "2018"

[dependencies]
actix-http = "=3.0.0-beta.10"
actix-web = "4.0.0-beta.9"
quickcheck = { version = "1.0.3", optional = true }
quickcheck_macros = { version = "1.0.0", optional = true }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.69"

[features]
test-traits = ["quickcheck", "quickcheck_macros"]
